webapi/src/FlugDemo/Controllers/FlugController.cs
using FlugDemo.Components;
using FlugDemo.Data;
using FlugDemo.Models;
using Microsoft.AspNet.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FlugDemo.Controllers
{
    
    public class FlugController: Controller
    {
        [FromServices]
        public IFlugRepository repo { get; set; }

        public FlugController()
        {
        }


        // /flug/Index
        // /flug
        public IActionResult Index() {
            var fluege = repo.FindAll();
            return View(fluege);
        }

        // /flug/edit/1
        public IActionResult Edit(int id) {
            var flug = repo.FindById(id);
            return View(flug);
        }

        [HttpPost]
        public IActionResult Edit(Flug flug)
        {
            repo.Save(flug);
            ViewBag.Message = "Flug wurde gespeichert!";
            return View(flug);
            //return View("Success", flug);
        }

    }
}

webapi/src/FlugDemo/Controllers/HomeController.cs
using Microsoft.AspNet.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FlugDemo.Controllers
{

    public class HomeController: Controller
    {
        public IActionResult Index() {
            // /Views/Home/Index
            return View();
        }
    }
}

webapi/src/FlugDemo/Views/Flug/Edit.cshtml
@model FlugDemo.Models.Flug

<h1>Detailansicht</h1>

<form asp-controller="Flug" asp-action="Edit">


    @if(!string.IsNullOrEmpty(ViewBag.Message)) {
        <div>
            @ViewBag.Message
        </div>
    }

    <div class="form-group">
        <label>Id</label>
        <input asp-for="Id" class="form-control" />
    </div>

    <div class="form-group">
        <label>AblugOrt</label>
        <input asp-for="AblugOrt" class="form-control" />
    </div>

    <div class="form-group">
        <label>ZielOrt</label>
        <input asp-for="ZielOrt" class="form-control" />
    </div>

    <div class="form-group">
        <label>Datum</label>
        <input asp-for="Datum" class="form-control" />

    </div>

    <div class="form-group">
        <label>FlugNr</label>
        <input asp-for="FlugNr" class="form-control" />
    </div>

    <div class="form-group">
        <input type="submit" class="btn btn-default" />
    </div>

</form>

webapi/src/FlugDemo/Views/Flug/Index.cshtml
@model IEnumerable<FlugDemo.Models.Flug>
<h1>Flüge</h1>
<table class="table table-striped">
    @foreach (var flug in Model)
    {
        <tr>
            <td>@flug.Id</td>
            <td>@flug.FlugNr</td>
            <td>@flug.AblugOrt</td>
            <td>@flug.ZielOrt</td>
            <td>@flug.Datum</td>
            <td><a asp-controller="Flug" asp-action="Edit" asp-route-id="@flug.Id">Edit</a></td>
        </tr>
    }
</table>

@section infos {
    (c) Manfred Steyer, 2016
}

webapi/src/FlugDemo/Views/Flug/Success.cshtml
<h1>Erfolgreich gespeichert!</h1>

<p>
    Daten wurden erfolgreich gespeichert!
</p>

webapi/src/FlugDemo/Views/Home/Index.cshtml
<h1>Hallo Welt!</h1>

<div>Willkommen zu dieser Demo-Anwendung!</div>

webapi/src/FlugDemo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title - Demo</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-controller="Home" asp-action="Index" class="navbar-brand">Demo</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-controller="Flug" asp-action="Index">Flüge</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            @RenderSection("infos", required: false)
        </footer>
    </div>

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("scripts", required: false)
</body>
</html>

webapi/src/FlugDemo/Views/Shared/_SimpleLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>

    <h1>Demo-Anwendung!</h1>

    <div>
        @RenderBody()
    </div>

    <hr />

    <div>
        @RenderSection("infos", required: false)
    </div>

</body>
</html>